### ISSUE TITLE
RNN backward function in evaluation error

### ISSUE THREAD

**Issue by choshin84** [harvardnlp/sa-vae#5]
trying to run sample code but getting below error.
appreciate your help

my environment is
Ubuntu 16.04.6 LTS
Pytorch 1.2.0
GPU Titan-V
Cuda version 10.1

Traceback (most recent call last):
  File "train_text.py", line 357, in <module>
    main(args)
  File "train_text.py", line 253, in main
    val_nll = eval(val_data, model, meta_optimizer)
  File "train_text.py", line 327, in eval
    var_params_svi = meta_optimizer.forward([mean_svi, logvar_svi], sents)
  File "/home/ubuntu/Program/sa-vae/optim_n2n.py", line 43, in forward
    return self.forward_mom(input, y, verbose)
  File "/home/ubuntu/Program/sa-vae/optim_n2n.py", line 90, in forward_mom
    all_grads_k = torch.autograd.grad(loss, all_input_params, retain_graph = True)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/autograd/__init__.py", line 149, in grad
    inputs, allow_unused)
RuntimeError: cudnn RNN backward can only be called in training mode

**Comment by HOLMEScdk** [comment]
Hi do you solve this?
