### ISSUE TITLE
Run VAE model returns error

### ISSUE THREAD

**Issue by khorshidisamira** [harvardnlp/sa-vae#6]
Hello,
I downloaded the dataset and then run 

`python preprocess_text.py --trainfile data/yahoo/train.txt --valfile data/yahoo/val.txt
--testfile data/yahoo/test.txt --outputfile `data/yahoo/yahoo`
 then when I want to run 
`python train_text.py --train_file data/yahoo/yahoo-train.hdf5 --val_file data/yahoo/yahoo-val.hdf5
--gpu 1 --checkpoint_path vae_model --model vae`
I am getting following error:

> python train_text.py --train_file data/yahoo/yahoo-train.hdf5 --val_file data/yahoo/yahoo-val.hdf5 --gpu 1 --model vae --checkpoint_path vae_model
Train data: 3211 batches
Val data: 398 batches
Word vocab size: 20001
model architecture
RNNVAE(
  (enc_word_vecs): Embedding(20001, 512)
  (latent_linear_mean): Linear(in_features=1024, out_features=32, bias=True)
  (latent_linear_logvar): Linear(in_features=1024, out_features=32, bias=True)
  (enc_rnn): LSTM(512, 1024, batch_first=True)
  (enc): ModuleList(
    (0): Embedding(20001, 512)
    (1): LSTM(512, 1024, batch_first=True)
    (2): Linear(in_features=1024, out_features=32, bias=True)
    (3): Linear(in_features=1024, out_features=32, bias=True)
  )
  (dec_word_vecs): Embedding(20001, 512)
  (dec_rnn): LSTM(544, 1024, batch_first=True)
  (dec_linear): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=1024, out_features=20001, bias=True)
    (2): LogSoftmax()
  )
  (dropout): Dropout(p=0.5, inplace=False)
  (dec): ModuleList(
    (0): Embedding(20001, 512)
    (1): LSTM(544, 1024, batch_first=True)
    (2): Sequential(
      (0): Dropout(p=0.5, inplace=False)
      (1): Linear(in_features=1024, out_features=20001, bias=True)
      (2): LogSoftmax()
    )
    (3): Linear(in_features=32, out_features=1024, bias=True)
  )
  (latent_hidden_linear): Linear(in_features=32, out_features=1024, bias=True)
)

> Starting epoch 1
> Traceback (most recent call last):
>   File "train_text.py", line 341, in <module>
>     main(args)
>   File "train_text.py", line 187, in main
>     train_nll_vae += nll_vae.data[0]*batch_size
> IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
> 

Any suggestions on how can I fix it?

**Comment by yoonkim** [comment]
Hi, I think the above error can be fixed by changing it to
```
train_nll_vae += nll_vae.item()*batch_size
```

Hope this helps!

**Comment by khorshidisamira** [comment]
> 
> 
> Hi, I think the above error can be fixed by changing it to
> 
> ```
> train_nll_vae += nll_vae.item()*batch_size
> ```
> 
> Hope this helps!

I changed all `.data[0]` to `.data` and it helped!:) 
thanks for comment!
